### PR TITLE
fix(config): Use proper token object

### LINKED ISSUE #971: Maxlen ignored - mpd
I tried setting both label-maxlen and specific label lengths but they are ignored..

ncmpcpp 0.8.1
mpd 0.20.15

image

### PR DESCRIPTION
**Pull request by patrick96**
When using the same token multiple times in the same label with
different length properties, polybar would always use the settings for
the first token. This now replaces the tokens one by one, so that a new
token object is used for the length settings each time a token is used
again. Because the token objects are added in order, the replacement
always uses the right token object for the token that is replaced.

Fixes #971

### CODE REVIEW

File: src/drawtypes/label.cpp [hunk 1]
```diff
@@ -47,14 +47,18 @@ namespace drawtypes {
     }
 
     for (auto&& tok : m_tokens) {
+      string repl = replacement;
```
Comment (NBonaparte) [inline src/drawtypes/label.cpp]: Brace initialization could be used here (`string repl{replacement}`).

Comment (patrick96) [reply src/drawtypes/label.cpp]: Sure thing! What would be the advantage of brace initialization over the equal sign in this case?

Comment (NBonaparte) [reply src/drawtypes/label.cpp]: Mainly for consistency, as it is generally used in the rest of the code.
