### PR TITLE
fix(date): date and time string limited to 63 chars

### LINKED ISSUE #744: Date module is limited to 63 chars
The string `date = AAAAAAAAAABBBBBBBBBBCCCCCCCCCCDDDDDDDDDDEEEEEEEEEEFFFFFFFFFFGGGGGGGGGGHHHHHHHHHHIIIIIIIIII` renders `AAAAAAAAAABBBBBBBBBBCCCCCCCCCCDDDDDDDDDDEEEEEEEEEEFFFFFFFFFFGGG` - this does not seem to be a limitation of `date`, as running `date +AAAAAAAAAABBBBBBBBBBCCCCCCCCCCDDDDDDDDDDEEEEEEEEEEFFFFFFFFFFGGGGGGGGGGHHHHHHHHHHIIIIIIIIII` outputs the exact input string.

This prevents me from using a date string like `%Y%%{F#5c6370}-%%{F-}%m%%{F#5c6370}-%%{F-}%d %H%%{F#5c6370}:%%{F-}%M%%{F#5c6370}:%%{F-}%S`.

### PR DESCRIPTION
**Pull request by patrick96**
Sensible upper limit of 1024 chars since anything of that length will
not be fully rendered on the bar anyways.

fixes #744

### CODE REVIEW

**Comment by patrick96** [comment]
Ah crap, I thought boost was already a dependency, but I guess this was back when this was still called lemonbuddy.
I'll fix this in the next few days

File: src/modules/date.cpp [hunk 1]
```diff
@@ -42,22 +42,26 @@ namespace modules {
...
-    strftime(time_buffer, sizeof(time_buffer), time_format.c_str(), localtime(&time));
+    // Clear stream contents
+    datetime_stream.str("");
+    datetime_stream << std::put_time(localtime(&time), time_format.c_str());
+    auto time_string = datetime_stream.str();
 
-    bool date_changed{strncmp(date_buffer, m_date.c_str(), sizeof(date_buffer)) != 0};
-    bool time_changed{strncmp(time_buffer, m_time.c_str(), sizeof(time_buffer)) != 0};
+    bool date_changed{strncmp(date_string.c_str(), m_date.c_str(), sizeof(date_string)) != 0};
+    bool time_changed{strncmp(time_string.c_str(), m_time.c_str(), sizeof(time_string)) != 0};
```
Comment (NBonaparte) [inline src/modules/date.cpp]: I think that since we are using strings and not char arrays anymore, we can use the `!=` operator. `sizeof` won't work here because it isn't a char array anyways.
