### PR TITLE
fix(builder): Respect label-ellipsis option

### LINKED ISSUE #1194: Can't disable ellipsis
From my MPD module config:
```ini
label-song          = %artist% - %title%
label-song-maxlen   = 22
label-song-ellipsis = false
```

But the ellipsis is still shown: screenshot_2018-04-26_01-28-48

### PR DESCRIPTION
**Pull request by patrick96**
As described in #1194 polybar never actually checks the m_ellipsis flag
in labels.

Right now, I have only refactored the builder to determine the actual
label text inside a function and added failing tests for that bug and
the general expected behaviour of get_label_text. This is why the
tests in the current build will fail.

This will probably decrease test coverage quite drastically, as codecov
doesn't track builder.cpp yet, so this basically adds a bunch of not
covered lines that codecov is now tracking

Also @NBonaparte, do you think the builder should throw an exception,
if the maxlen is less than the length of the ellipsis and ellipsis is
enabled, because it would be impossible to follow both the label-maxlen
and the label-ellipsis directive?

EDIT1: Seems like the new test doesn't build on travis, and for some reason the travis build doesn't fail when this happens.
EDIT2: I have fixed the compilation error, now the test should fail for the right reasons
EDIT3: Fixes #1194

### CODE REVIEW

**Comment by patrick96** [comment]
Hold off on merging this, I think we should just log a warning and disable ellipsis, if the maxlen < 3

**Comment by patrick96** [comment]
I think this is ready for review now.

**Comment by patrick96** [comment]
> What if we used an ellipsis character ("…") instead of three periods?

This will be what I implement next, in a separate PR, a config option to define the ellipsis.

**Comment by M1dgard** [comment]
Configurable ellipsis = #1195

**Comment by M1dgard** [comment]
I tested this patch as a user, I didn't find any issue. Beware that it changes behaviour (that's intended, and I requested this change in #1195): `maxlen 4` used to yield `abcd...`, now it yields `a...`

File: src/drawtypes/label.cpp [hunk 1]
```diff
@@ -221,6 +221,17 @@ namespace drawtypes {
       }
     }
 
+    size_t maxlen = conf.get(section, name + "-maxlen", 0_z);
+    bool ellipsis = conf.get(section, name + "-ellipsis", true);
+
+    if(ellipsis && maxlen > 0 && maxlen < 3) {
+      logger::make().err(sstream() << "Label " << section << "." << name
```
Comment (NBonaparte) [inline src/drawtypes/label.cpp]: Couldn't we throw an `application_error` or some other type of error to avoid creating a new logger?

Comment (patrick96) [reply src/drawtypes/label.cpp]: `logger::make` uses the singleton pattern, so only the first call to `logger::make()` will create a new instance, all others always return the same instance. I used it directly because I didn't want to add the `m_log` field just for that.. Btw. I really don't like the use of a singleton for the logger but that is a discussion for another time.

If we threw an `application_error` here, wouldn't it be caught in the controller and would disable the whole module? I was debating, if we wanted invalid maxlen be a fatal error, would you prefer that?

Comment (NBonaparte) [reply src/drawtypes/label.cpp]: Yeah, I think that would be much neater.

Comment (patrick96) [reply src/drawtypes/label.cpp]: Alright, gonna revert back to throwing an error when I have the time

Comment (patrick96) [reply src/drawtypes/label.cpp]: Done
