### PR TITLE
xworkspace support window manager with less names than desktops

### LINKED ISSUE #248: Provide default desktop names
In ```get_desktop_names``` in the ```ewmh_util```, it would be better to provide some default names and use ```_NET_NUMBER_OF_DESKTOPS``` as count.
According to https://specifications.freedesktop.org/wm-spec/latest/ar01s03.html, the number of given names can be less than the actual number of desktops.

### LINKED ISSUE #1491: module/ewmh does not detect removed workspaces in openbox
## Describe the issue
Removed workspaces in openbox are not removed from the workspace list in the ewmh module.

**Expected behavior:**
When workspaces are removed in the WM, it should also be removed from the list.

**Actual behavior:**

When workspaces are added in the WM, they are added to the list. When they are removed in the WM, they stay in the list. 

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```dosini
[bar/example]
width = 100%
height = 40
offset-x = 0
offset-y = 0
radius = 0
fixed-center = false
underline-size = 0

modules-left = ewmh 
modules-center = 
modules-right = 

[module/ewmh]
type = internal/xworkspaces

pin-workspaces = true

enable-click = true 

enable-scroll = false
```
*List any other steps needed to reproduce the issue besides starting polybar with the config you posted above.*

## Polybar Log
*Post everything polybar outputs to the terminal when you run it and the issue occurs below*
```

```

## Screenshots
Default workspaces:

After adding a workspace

After removing the added workspace

## Environment:
* WM: Openbox
* Output of `polybar -vvv`:
```
polybar 3.1.0-git

Features: +alsa +curl -i3 -mpd +network

X extensions: +randr (+monitors) -render -damage -sync -composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -Werror -Wno-noexcept-type -O2 -pedantic -pedantic-errors
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```
## Additional context
It doesn't matter if the workspace is added with ObConf, with the middleclick menu or using `wmctrl -n 5`

### PR DESCRIPTION
**Pull request by frstrikerman**
TEAMEDIT:
Fixes #1491 
Fixes #248
Closes #904

### CODE REVIEW

**Comment by frstrikerman** [comment]
I made those change while this issue wasn't fixed : https://github.com/jaagr/polybar/issues/1462
It might be irrelevant now

**Comment by patrick96** [comment]
Awesome, so this basically makes the xworkspaces module conformant to [this](https://specifications.freedesktop.org/wm-spec/wm-spec-latest.html#idm140200472706208) section of the ewmh spec?

**Comment by frstrikerman** [comment]
Yes

**Comment by patrick96** [comment]
Alright it's on my todo list. Might be a while though.

**Comment by frstrikerman** [comment]
I just checked and one part of the spec is missing when there is more names than dekstops. I will try to implement it during this week

**Comment by patrick96** [comment]
Great. Thanks a lot for helping out!

File: src/x11/ewmh.cpp [hunk 1]
```diff
@@ -77,6 +77,13 @@ namespace ewmh_util {
     return desktop;
   }
 
+  unsigned int get_number_of_desktops(int screen) {
+    auto conn = initialize().get();
+    unsigned int desktops = XCB_NONE;
```
Comment (patrick96) [inline src/x11/ewmh.cpp]:
```suggestion
    uint32_t desktops = 0;
```

File: src/x11/ewmh.cpp [hunk 2]
```diff
@@ -77,6 +77,13 @@ namespace ewmh_util {
     return desktop;
   }
 
+  unsigned int get_number_of_desktops(int screen) {
```
Comment (patrick96) [inline src/x11/ewmh.cpp]: Just to make it consistent with what `xcb_ewmh.h` uses.

```suggestion
  uint32_t get_number_of_desktops(int screen) {
```

File: src/modules/xworkspaces.cpp [hunk 3]
```diff
@@ -219,6 +219,21 @@ namespace modules {
     }
   }
 
+  vector<string> xworkspaces_module::get_desktop_names(){
+    vector<string> names = ewmh_util::get_desktop_names();
+    unsigned int desktops_number = ewmh_util::get_number_of_desktops();
```
Comment (patrick96) [inline src/modules/xworkspaces.cpp]:
```suggestion
    uint32_t desktops_number = ewmh_util::get_number_of_desktops();
```

File: include/x11/ewmh.hpp [hunk 4]
```diff
@@ -24,6 +24,7 @@ namespace ewmh_util {
   vector<position> get_desktop_viewports(int screen = 0);
   vector<string> get_desktop_names(int screen = 0);
   unsigned int get_current_desktop(int screen = 0);
+  unsigned int get_number_of_desktops(int screen = 0);
```
Comment (patrick96) [inline include/x11/ewmh.hpp]:
```suggestion
  uint32_t get_number_of_desktops(int screen = 0);
```

**Comment by patrick96** [comment]
Oh and I forgot to mention this, please always use curly braces for if-blocks, even id they're only a single line

**Comment by frstrikerman** [comment]
I wasn't able to work on this because I had exams

File: src/x11/ewmh.cpp (hunk 1 above)
Comment (patrick96) [reply src/x11/ewmh.cpp]: Fair enough, we don't really need to do this here. I added an entry in our refactoring project to use fixed width integers for everything that interacts with EWMH since the EWMH spec defines the bit-width of the numbers.
